application: cranulator
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /glass/(.*\.(html|css|js|grxml))
  static_files: emulator/static/\1
  upload: emulator/static/(.*\.(html|css|js|grxml))

- url: /glass/images/*.png
  static_dir: emulator/static/images
  mime_type: image/png  

- url: /glass/images
  static_dir: emulator/static/images

- url: /_ah/spi/.*
  script: mirror_api.api.ApiServer

- url: /images/*.png  
  static_dir: service/static/images
  mime_type: image/png

- url: /images
  static_dir: service/static/images

- url: /service/(.*\.(html|css|js))
  static_files: service/static/\1
  upload: service/static/(.*\.(html|css|js))

- url: /upload/.*
  script: mirror_api.upload.app

- url: .*
  script: main.app

libraries:
- name: pycrypto
  version: latest

- name: jinja2
  version: latest

- name: PIL
  version: latest
